import type { Metadata } from "next";
import { Radley, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Image from "next/image";
import Container from "@/components/Container";
import HomeBackground from "@/components/HomeBackground";

const radley = Radley({
  variable: "--font-radley",
  subsets: ["latin"],
  weight: "400",
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${radley.variable} ${plusJakartaSans.variable} antialiased`}
      >
        <HomeBackground>
          <Container>
            <Header />
          </Container>
        </HomeBackground>

        {children}
      </body>
    </html>
  );
}
